-- Replace all people with canonical seed (97). Clears allocations first.
DELETE FROM allocations;
DELETE FROM people;

INSERT INTO people (id, name, email, role, department, access, tags, type, cost_rate, bill_rate, start_date, end_date, work_type, notes, holidays, archived)
VALUES
(1, 'Aditi Bali', 'aditi.bali@company.com', '—', 'Fire Nation', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(2, 'Akhil Prasad', 'akhil.prasad@company.com', 'Graduate', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(3, 'Ali Raza', 'ali.raza@company.com', 'Senior Consultant', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(4, 'Amisha Punj', 'amisha.punj@company.com', 'Consultant', 'Transition', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(5, 'Amy Schroter', 'amy.schroter@company.com', 'Senior Consultant', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(6, 'Amy Yienni Liu', 'amy.liu@company.com', 'Engineer', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(7, 'Andrew Charles Millard Brown', 'andrew.brown@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(8, 'Ankit Patel', 'ankit.patel@company.com', 'Senior Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(9, 'Ashish Dubey', 'ashish.dubey@company.com', 'Senior Specialist Lead', 'Hornets', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(10, 'Asmita Sayanthan', 'asmita.sayanthan@company.com', 'Graduate', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(11, 'Belinda Chan', 'belinda.chan@company.com', 'Senior Consultant', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(12, 'Belinda Wakefield', 'belinda.wakefield@company.com', 'Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(13, 'Bob Chu', 'bob.chu@company.com', 'Senior Consultant', 'Hornets', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(14, 'Brad Hedley', 'brad.hedley@company.com', 'Senior Specialist Lead', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(15, 'Brayden Chan', 'brayden.chan@company.com', 'Graduate', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(16, 'Caleb Barber', 'caleb.barber@company.com', 'Senior Consultant', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(17, 'Charmi Raval', 'charmi.raval@company.com', 'Engineer', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(18, 'Chris Lenton', 'chris.lenton@company.com', 'Senior Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(19, 'Christopher David Whatman', 'christopher.whatman@company.com', 'Senior Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(20, 'Dale Stirling', 'dale.stirling@company.com', 'Director', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(21, 'Damien Ian Penny', 'damien.penny@company.com', 'Senior Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(22, 'Dan Scott', 'dan.scott@company.com', 'Consultant', 'Beans', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(23, 'Diana Hopkins', 'diana.hopkins@company.com', 'Director', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(24, 'Doris Che', 'doris.che@company.com', 'Consultant', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(25, 'Elizabeth Santhiyagu', 'elizabeth.santhiyagu@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(26, 'Frances Johnson', 'frances.johnson@company.com', 'Graduate', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(27, 'Geoff Hargreaves', 'geoff.hargreaves@company.com', 'Manager', 'Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(28, 'Glenn Wimetal', 'glenn.wimetal@company.com', 'Manager', 'Transition', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(29, 'Harry Michalides', 'harry.michalides@company.com', 'Senior Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(30, 'Harshil Patel', 'harshil.patel@company.com', 'Engineer', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(31, 'Harshitha Papa', 'harshitha.papa@company.com', 'Consultant', 'Fire Nation', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(32, 'Jamie Arnold', 'jamie.arnold@company.com', 'Senior Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(33, 'Jay Cherukuri', 'jay.cherukuri@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(34, 'Jenna Rachelle Matthews', 'jenna.matthews@company.com', 'Specialist Director', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(35, 'Jincy Joseph', 'jincy.joseph@company.com', 'Senior Consultant', 'Hornets', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(36, 'Joey Brown', 'joey.brown@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(37, 'Johan Peter Klaassen', 'johan.klaassen@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(38, 'John Fan', 'john.fan@company.com', 'Manager', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(39, 'Joshua Agostino', 'joshua.agostino@company.com', 'Consultant', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(40, 'Joshua Joseph Kneller', 'joshua.kneller@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(41, 'Joshua Matthew Brennan', 'joshua.brennan@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(42, 'Karen Gosalim', 'karen.gosalim@company.com', 'Consultant', 'Beans', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(43, 'Karunakar Challa', 'karunakar.challa@company.com', 'Manager', 'Fire Nation', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(44, 'Katrina Chapman', 'katrina.chapman@company.com', 'Specialist Director', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(45, 'Kenneth Charles Poole', 'kenneth.poole@company.com', 'Senior Specialist Lead', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(46, 'Kirti Wadekar', 'kirti.wadekar@company.com', 'Senior Consultant', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(47, 'Lauren Langer', 'lauren.langer@company.com', 'Manager', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(48, 'Lorna Mulcahy', 'lorna.mulcahy@company.com', '—', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(49, 'Manasi Thakur', 'manasi.thakur@company.com', 'Senior Consultant', 'Transition', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(50, 'Martin Su', 'martin.su@company.com', 'Consultant', 'Beans', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(51, 'Matthew Perrella', 'matthew.perrella@company.com', 'Manager', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(52, 'Max Lai', 'max.lai@company.com', 'Consultant', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(53, 'Mehreen Qadri', 'mehreen.qadri@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(54, 'Michael Li', 'michael.li@company.com', 'Consultant', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(55, 'Mihir Rajpal', 'mihir.rajpal@company.com', 'Manager', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(56, 'Mina Ibrahim', 'mina.ibrahim@company.com', 'Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(57, 'Mohamed Mansour', 'mohamed.mansour@company.com', 'Senior Consultant', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(58, 'Muhammad Awais', 'muhammad.awais@company.com', 'Senior Consultant', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(59, 'Nicole Strugnell', 'nicole.strugnell@company.com', 'Senior Consultant', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(60, 'Oliver Zhou', 'oliver.zhou@company.com', 'Senior Consultant', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(61, 'Paul William Davies', 'paul.davies@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(62, 'Pradeep Tupili', 'pradeep.tupili@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(63, 'Pranavi Sudhindra', 'pranavi.sudhindra@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(64, 'Ravi Baliga', 'ravi.baliga@company.com', 'Specialist Lead', 'Hornets', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(65, 'Ross McGarel', 'ross.mcgarel@company.com', 'Manager', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(66, 'Ryan Howard', 'ryan.howard@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(67, 'Ryan Kurtz', 'ryan.kurtz@company.com', 'Graduate', 'Beans', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(68, 'Sai Harish Reddy Gantada', 'sai.gantada@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(69, 'Sajid Abbasi', 'sajid.abbasi@company.com', 'Consultant', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(70, 'Sandeep Karun', 'sandeep.karun@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(71, 'Sarvesh Singh', 'sarvesh.singh@company.com', 'Graduate', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(72, 'Scott Subbaiah', 'scott.subbaiah@company.com', 'Specialist Lead', 'Sky', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(73, 'Sheher Yar', 'sheher.yar@company.com', 'Graduate', 'Fire Nation', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(74, 'Shu Chia', 'shu.chia@company.com', 'Consultant', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(75, 'Shweta Sharma', 'shweta.sharma@company.com', 'Senior Consultant', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(76, 'Siriwardena, Shevin', 'siriwardena.shevin@company.com', 'Manager', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(77, 'Sithum Dissanayake', 'sithum.dissanayake@company.com', 'Graduate', 'Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(78, 'Siva Sankar Reddy Katasani', 'siva.katasani@company.com', 'Manager', 'Fire Nation', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(79, 'Sonal Chouksey', 'sonal.chouksey@company.com', 'Analyst', 'Deloitte India - Eaas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(80, 'Sourabh Shukla', 'sourabh.shukla@company.com', 'Senior Consultant', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(81, 'Sritama Mahanty', 'sritama.mahanty@company.com', 'Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(82, 'Steven Sagayaraj', 'steven.sagayaraj@company.com', 'Senior Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(83, 'Tanvi Vinayaraj', 'tanvi.vinayaraj@company.com', 'Engineer', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(84, 'Thanh Duong', 'thanh.duong@company.com', 'Senior Consultant', 'Meatballs', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(85, 'Thersea Roth', 'thersea.roth@company.com', 'Graduate', 'Data & AI', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(86, 'Tiarna Ryan', 'tiarna.ryan@company.com', 'Senior Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(87, 'Tracey Kirby', 'tracey.kirby@company.com', 'Senior Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(88, 'Trent Bartlem', 'trent.bartlem@company.com', 'Manager', 'Beans', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(89, 'Twisha Parekh', 'twisha.parekh@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(90, 'Vani Kamisetty', 'vani.kamisetty@company.com', 'Senior Consultant', '', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(91, 'Vasudha Saha', 'vasudha.saha@company.com', '—', 'Ninjas', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(92, 'Venkata Malladi', 'venkata.malladi@company.com', 'Manager', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(93, 'Victor Ikeh', 'victor.ikeh@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(94, 'Vijay Sriram', 'vijay.sriram@company.com', 'Manager', 'Anger Management', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(95, 'Vivian Jia', 'vivian.jia@company.com', 'Consultant', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(96, 'Wesley Chapman', 'wesley.chapman@company.com', 'Consultant', 'Sliced Secure', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false),
(97, 'Wisith Halpandeniya', 'wisith.halpandeniya@company.com', 'Engineer', 'Azkaban', '—', ARRAY[]::text[], 'Employee', '0', '0', '2026-01-01', '', 'Full-time', '', 'None', false);

-- Extra lookup values used by seed but not in earlier migrations
INSERT INTO lookup_roles (name) VALUES
  ('Analyst'),
  ('Senior Manager'),
  ('Specialist Director'),
  ('Specialist Lead')
ON CONFLICT (name) DO NOTHING;

INSERT INTO lookup_depts (name) VALUES
  ('Eaas'),
  ('Deloitte India - Eaas')
ON CONFLICT (name) DO NOTHING;
